### ISSUE TITLE
Caster.io functional programming course missing files

### ISSUE THREAD

**Issue by palkakrzysiek** [JorgeCastilloPrz/KotlinAndroidArchitecture#19]
Hello,

thank you for the great course! I see some files (like monad-stack/src/main/java/com/github/jorgecastillo/kotlinandroid/TypeConstructors.kt) you had used while you were recording lessons in the casterio branch, but some are missing like
![image](https://user-images.githubusercontent.com/1042608/36339783-dcddc298-13c4-11e8-8997-e32b8c227b6c.png)
Is it on purpose, or will those be available in this public repository in the future?

**Comment by JorgeCastilloPrz** [comment]
Those were created in intermediate steps of the repository so I'm afraid that's not available anymore, since this repo intends to be more like a blueprint on how to write Android apps using Arrow.
