### ISSUE TITLE
Questions about unit test and cache

### ISSUE THREAD

**Issue by TonyTangAndroid** [JorgeCastilloPrz/KotlinAndroidArchitecture#20]
I have read the code in monad-stack sample. And I would like to raise two questions:

1, The presenter is including the context, which is conflicted in clean architecture because presenter and domain should be pure java library.  I reckon this could be resolved if you do not introduce context in the SuperHeroesContext as we actually never used it. If you remove the context in SuperHeroesContext, we are not going to implement data cache as data cache will be definitely bound together with Android.  How to resolve such issue?

2, To avoid introducing side effects, we are addressing errors and success result in presenter level. What we about cache? We must be done from data level, which will introduce side effects. How are we to support a bit more complicated sample with cache?

**Comment by leandroBorgesFerreira** [comment]
Hello @TonyTangAndroid. I am also reading this repository and I am finding it very interesting. I have an opinion about the first question you make.

You don't need the pass context in the SuperHeroContext, as you already noticed. About the cache, you can pass just a interface in the SuperHeroContext to deal with your cache and use it in the model layer. Although the implementation is related to the Android SDK, this is abstracted away by the interface. You can use this same approach to every complex scenario, you will may just end up with more dependencies in your Monad.

**Comment by JorgeCastilloPrz** [comment]
I'm closing this sine the project is quite different atm. I've bumped it to Arrow 0.10.2 and there's an example of how to replace dependencies in tests now [here](https://github.com/JorgeCastilloPrz/ArrowAndroidSamples/blob/72ede82473ba954060f9a8b454e0a6e419aa2a70/app/src/test/java/com/github/jorgecastillo/kotlinandroid/io/algebras/data/network/NetworkServiceIntegrationTests.kt#L30). Hopefully it helps!

**Comment by TonyTangAndroid** [comment]
Sorry for not following up after the issue is posted. And thank you @leandroBorgesFerreira & @JorgeCastilloPrz for the update. I will revisit the sample app again in the coming Christmas holiday and absorb these new tips and changes.
