### ISSUE TITLE
Add tests for tagless-final

### ISSUE THREAD

**Issue by skrabacz-michal** [JorgeCastilloPrz/KotlinAndroidArchitecture#21]
Could you add tests for the tagless-final approach? To show how to mock/stub e.g. API requests?

**Comment by JorgeCastilloPrz** [comment]
Hey @skrabacz-michal, I'm sorry that took so long but I've bumped the project to last Arrow release (0.10.2) plus refactored a bunch of things and added some API Integration tests so you can see how to replace stuff at runtime.

[Here you have the tests](https://github.com/JorgeCastilloPrz/ArrowAndroidSamples/blob/72ede82473ba954060f9a8b454e0a6e419aa2a70/app/src/test/java/com/github/jorgecastillo/kotlinandroid/io/algebras/data/network/NetworkServiceIntegrationTests.kt#L30).

Closing this for now.
