### ISSUE TITLE
It seems that the old file name did not change.

### ISSUE THREAD

**Issue by galcyurio** [JorgeCastilloPrz/KotlinAndroidArchitecture#28]
There are `HeroesUseCases.kt` and `HeroesRepository.kt` files.

- [algebras.business.HeroesUseCases.kt](https://github.com/JorgeCastilloPrz/ArrowAndroidSamples/blob/master/app/src/main/java/com/github/jorgecastillo/kotlinandroid/io/algebras/business/HeroesUseCases.kt)
- [algebras.data.HeroesRepository.kt](https://github.com/JorgeCastilloPrz/ArrowAndroidSamples/blob/master/app/src/main/java/com/github/jorgecastillo/kotlinandroid/io/algebras/data/HeroesRepository.kt)

ps. Thanks for migration to 0.10.x

**Comment by JorgeCastilloPrz** [comment]
True! A PR for changing those file names to be something like `UseCases.kt` and `Repository.kt` would be welcome. Otherwise I'll do it by myself!
